import React from 'react';

export const About: React.FC = () => {
  return (
    <div className="flex flex-col h-full bg-slate-900 border border-slate-700 rounded-xl overflow-hidden shadow-2xl max-w-4xl mx-auto">
      <div className="px-8 py-8 md:py-12 bg-slate-800/50">
        <h1 className="text-3xl font-bold text-white mb-4">
          Understanding the NCBI SRA Validator AI
        </h1>
        <p className="text-lg text-slate-300 leading-relaxed max-w-2xl">
          Think of this application as a <span className="text-brand-400 font-semibold">Flight Simulator for DNA Data</span> designed to optimize cloud operations for the world's largest biological databases.
        </p>
      </div>

      <div className="p-8 space-y-12 overflow-y-auto custom-scrollbar">
        
        {/* Section 1: The Ecosystem */}
        <section className="space-y-4">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-blue-500/20 rounded-lg">
               <svg className="w-6 h-6 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>
            </div>
            <h2 className="text-xl font-semibold text-white">The Federal Ecosystem: NIH, NLM, and NCBI</h2>
          </div>
          <p className="text-slate-400 leading-relaxed">
            The <strong>National Institutes of Health (NIH)</strong> is the primary U.S. federal agency for medical research. Within the NIH lies the <strong>National Library of Medicine (NLM)</strong>, the world's largest biomedical library. 
            <br/><br/>
            Operating under the NLM is the <strong>National Center for Biotechnology Information (NCBI)</strong>. The NCBI is responsible for hosting the massive databases that store the genetic blueprints of life, serving as the digital library for biological discovery.
          </p>
        </section>

        {/* Section 2: Big Data & SRA */}
        <section className="space-y-4">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-purple-500/20 rounded-lg">
               <svg className="w-6 h-6 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" /></svg>
            </div>
            <h2 className="text-xl font-semibold text-white">The SRA: Petabytes of DNA Data</h2>
          </div>
          <p className="text-slate-400 leading-relaxed">
            The <strong>Sequence Read Archive (SRA)</strong> is the largest publicly available repository of high-throughput sequencing data. It stores raw DNA sequencing data generated by Next-Generation Sequencing (NGS) platforms like <em>Illumina</em>, <em>PacBio</em>, and <em>Oxford Nanopore</em>.
            <br/><br/>
            This database is measured in <strong>Petabytes (PB)</strong>—that's millions of Gigabytes. Managing this data requires massive cloud infrastructure (AWS STRIDES, Google Cloud Platform) and rigorous validation to ensure scientific integrity.
          </p>
        </section>

        {/* Section 3: The Problem */}
        <section className="space-y-4">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-red-500/20 rounded-lg">
               <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
            </div>
            <h2 className="text-xl font-semibold text-white">The Challenge</h2>
          </div>
          <p className="text-slate-400 leading-relaxed">
            Ingesting and validating genomic data at this scale is expensive and time-consuming. 
            Running quality checks (like FASTQC) on a 10TB dataset can take days and cost thousands of dollars in cloud compute time. If a file is corrupted, discovering it <em>after</em> processing is a massive waste of resources.
          </p>
        </section>

        {/* Section 4: The Solution */}
        <section className="space-y-4">
          <div className="flex items-center gap-3 mb-2">
             <div className="p-2 bg-green-500/20 rounded-lg">
               <svg className="w-6 h-6 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
             </div>
            <h2 className="text-xl font-semibold text-white">How This Tool Helps</h2>
          </div>
          <p className="text-slate-400 leading-relaxed">
            This application acts as a pre-flight checklist and simulation engine for Technical Program Managers (TPMs) and Bioinformaticians. It allows users to:
          </p>
          <ul className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
            <li className="bg-slate-800 p-4 rounded-lg border border-slate-700/50">
              <strong className="text-brand-300 block mb-1">Predict Cloud Costs</strong>
              <span className="text-sm text-slate-400">Estimate storage and egress fees for AWS S3 and Google BigQuery based on file size.</span>
            </li>
            <li className="bg-slate-800 p-4 rounded-lg border border-slate-700/50">
              <strong className="text-purple-300 block mb-1">Verify Data Integrity</strong>
              <span className="text-sm text-slate-400">Simulate checksum verifications and header analysis to catch corruption early.</span>
            </li>
            <li className="bg-slate-800 p-4 rounded-lg border border-slate-700/50">
              <strong className="text-blue-300 block mb-1">Analyze Quality (Phred)</strong>
              <span className="text-sm text-slate-400">Visualize Q-Scores to determine if DNA reads are accurate enough for research.</span>
            </li>
            <li className="bg-slate-800 p-4 rounded-lg border border-slate-700/50">
              <strong className="text-teal-300 block mb-1">Bioinformatics AI</strong>
              <span className="text-sm text-slate-400">Leverage Gemini AI to generate Python validation scripts and answer technical questions.</span>
            </li>
          </ul>
        </section>

        {/* Credit Section */}
        <div className="mt-12 pt-8 border-t border-slate-800 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-slate-500 text-sm">
            NCBI SRA Validator AI v1.2.0
          </p>
          <div className="flex items-center gap-2 bg-slate-800/50 px-4 py-2 rounded-full border border-slate-700">
            <span className="text-slate-400 text-sm">Coded by</span>
            <a 
              href="https://kevinroozrokh.com" 
              target="_blank" 
              rel="noopener noreferrer"
              className="bg-clip-text bg-gradient-to-r from-brand-400 to-indigo-400 font-semibold hover:opacity-80 transition-opacity text-sm"
            >
              Kevin Roozrokh
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};
